language: python

python:
  - 3.6

install:
    # Install the Python dependencies
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - export EMAIL_HOST_PASSWORD='test'
  - psql -c 'create database awesomedb;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - coverage run --source=manage_event manage.py test manage_event
after_success: coveralls


