language: python

python:
  - 3.6

install:
    # Install the Python dependencies
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database awesomedb;' -U postgres

script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test


