language: python

python:
  - 3.6

install:
    # Install the Python dependencies
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c 'create database mytestdatabase;' -U postgres

script:
  - python manage.py test


